### ISSUE TITLE
Performance problem with latest update

### ISSUE THREAD

**Issue by carlocardella** [mtbaqer/vscode-better-folding#15]
Type: <b>Bug</b>

The latest update seems to have serious performance problems: tested on both VSCode latest Insiders and Stable on two different Windows machines. 

Typing is very slow to respond, letters appears seconds after being typed; the overall CPU utilization is normal for the machine.

Disabling the extension resolves the problem.

Extension version: 0.2.2
VS Code version: Code - Insiders 1.75.0-insider (b229eb5fa2ecadb8a5238ccb9f6f49f7ccba9d2b, 2023-01-27T22:17:10.413Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.57GB (12.61GB free)|
|Process Argv|--crash-reporter-id a979586f-c5b5-4646-91b6-e3918bf5fa50|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887

```

</details>

**Comment by carlocardella** [comment]
This may be due to a conflict with another extension; I tried to disable all my extensions except Better Folding and I cannot repro anymore...
I'll re-enable my extensions one by one, hopefully that will show where the conflict is

**Comment by mtbaqer** [comment]
Thanks for reporting the problem. Yes do keep me updated please. And would you mind checking if the conflict happens for both versions or just specifically with the new one?

**Comment by carlocardella** [comment]
This is curious... So, I found the conflicting extension: [DrMerfy.overtype](https://github.com/DrMerfy/vscode-overtype). 

Anyway, I can repro the problem only if:

1. _Both_ `OverType` and `Better Folding` are enabled, **and**
2. I am working on a _long_ document (I am not identified yet how long, I was working on a doc with ~400 lines when I noticed the behavior)

I thought the actual problem was with `OverType`, **but** if I disable `Better Folding` and keep `OVerType` then I can work just fine with much longer documents. Then moment I re-enalbe `Better Folding` the problem comes back. 
Also, with both extensions enabled I can work just fine with smaller documents (50-100 lines), the lag becomes noticeable ardoun 250-300 lines.

So there is some kind of weird interaction between the two extensions, I assume both do some type of document parsing and with longer documents they stumble on some bottlened/inefficient regex or something along those lines.

I am not sure how to go forward from here but if you need me to run some more tests I'll be happy to help; I have created an issue for `OverType` as well: https://github.com/DrMerfy/vscode-overtype/issues/34

**Comment by mtbaqer** [comment]
Just pushed a new update 0.3.1 that have a little performance boost. Would you mind trying it and see if it makes it any better?

**Comment by carlocardella** [comment]
Not fully solved but it is going in the right direction. Here's what I tested:

1. Both Better Folding and OverType enabled in a plaintext file: no issues. This is an improvement, I was able to repro with this simple configuration before this update
2. Both Better Folding and OverType enabled in one of my usual Typescript projects: I can still repro and the performance issue is still pretty bad
3. Only Better Folding enabled in the same Typescript project: so far works well. I had a slight performance issue with this configuration earlier (even if not as bad as with point 2) and that seems to be gone now

So, as you said, there is a performance improvement; I am going to keep Better Folding enabled for a while (without OverType for the time being).

**Comment by GammaGames** [comment]
I'm also getting a **lot** of performance issues on large files. There's a lot of flickering when I scroll and sometimes the whole window freezes until all the folded text has rendered. I disabled all other extensions and still have the issue:

![Peek 2023-02-07 10-23](https://user-images.githubusercontent.com/7832163/217318407-dd499ca9-e77c-4477-8dd1-a469005866f1.gif)

**Comment by mtbaqer** [comment]
Just published 0.4.0 which should be significantly faster. Let me know if it is any better.

**Comment by AlexanderTheGr8-gr** [comment]
Hello, I am coming here with my turn, to report too that this extension makes working with V.Code TOO slow :/

When I found out about this extension I was laughing out of joy for QUITE some time..
But eventually trying to use it, it lags my work to a stop.

Startup time: ~13 seconds.
But when profiling to see the actual time it takes when I am working, for a specidfic instant it stuck for 30 seconds(!) O.O .... I was only trying to replace a ♦ char with another ♦ char (selected it, and pressed alt-4) and that made me wait 30 seconds. Profiling the extensions showed that it was on this extension the time I was waiting.

Since you, the dev.(s)  said you are tracking performance here, I am replying here instead of new issue.
I also link other issues here to help you gather it together: #43 , #42 , #20 



My issue:
**Describe the bug**
Profiling times:
Plugin stat time: ~15sec
Plugin profilling time for changing a single char: ~30 sec

**To Reproduce**
Steps to reproduce the behavior:
1. Open a file containing 3.500 lines, with \~230589 chars, with many many many folds (not so many nest levels, 5~6 at most)
2. Try to write something...
3. Boom, you are stuck waiting for V.Code to actually type what you wrote
4. Disable the plugin
5. Problem is gone

(4. and 5. are useless to state, since I gave you profiling times, but just to make sure you don't distrust)

**Expected behavior**
V.Code should not lag this much because I installed an extension

Screenshots: Private data.. sorry, can't

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - V.Code: 1.77.3
![image](https://github.com/mtbaqer/vscode-better-folding/assets/16266778/23fc2487-2ac6-4a77-9513-13f34771fe6a)
- RAM: 8GB
- CPU: Intel Core i5-4210U
- GPU: NVIDIA GeForce 820M

**Comment by GammaGames** [comment]
Nice stats @alexNecroJack, I stopped using this extension because of the lengthy startup times. I'm hopping between projects too frequently to be waiting >10s to get started any time I have to open a workspace

**Comment by forivall** [comment]
Parsing should be done in a language server to fully resolve performance issues.
