### ISSUE TITLE
Folding the code after the part '...' is shown overlapping with the code

### ISSUE THREAD

**Issue by iejzh** [mtbaqer/vscode-better-folding#63]
**Describe the bug**
Folding the code after the part '...' is shown overlapping with the code.

**To Reproduce**
sample code：
```
RequestLockMutex &Server::TestsGenServiceImpl::getLock() {
    std::string const &client = RequestEnvironment::getClientId();
    auto [iterator, inserted] = locks.try_emplace(client);
    return iterator->second;
}
```

**Screenshots**
<img width="714" src="https://github.com/user-attachments/assets/e020eb95-49ce-4899-8d43-667f51476852">
Note the three points of overlap on the RequestLockMutex.

**Desktop (please complete the following information):**
 - OS: MACOS 14 
 - VScode 1.91
 - Plugin Version [v0.5.1]

**Comment by song-dog** [comment]
@iejzh I noticed this at some point in the last 4-5 months but part of me thinks it's just always been that way and that's just when I realized it. Anyway, it turns out it's a very easy fix. In [/src/decorators/betterFoldingDecorator.ts](https://github.com/mtbaqer/vscode-better-folding/blob/main/src/decorators/betterFoldingDecorator.ts#L42), line 42 needs to be changed from
```typescript
`margin: `0 -${90}% 0 0`
```
to
```typescript
margin: `0 -${100}% 0 0`
```
This effectively hides the ellipsis outside the visible area without removing the ability to unfold.
